# File: src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:28057/railway
    username: root
    password: PPCEaUisOfakkHrxDjmkDIQeMoZjGGum
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "ReplaceThisWithAStrongRandomSecretKey_AtLeast_32_Chars"
  expiration-minutes: 30
server:
  port: 8585

odoo:
  api:
    url: https://nonpurposive-nonpendently-deloras.ngrok-free.dev
    database: Ree-database
    username: chaimaayaqine27@gmail.com
    password: openpgpwd

